#ifndef CBrowserPixmaps_H
#define CBrowserPixmaps_H

static const char *
noimage[] = {
  "35 35 8 1",
  ". c #000000",
  "# c #ffffff",
  "a c #baa0a7",
  "b c #c0c0c0",
  "c c #808080",
  "d c #2f7e88",
  "e c #1a5f67",
  "  c none",
  "                                   ",
  "                                   ",
  "  #######################ba        ",
  "  ######################b##a       ",
  "  ##bbbbbbbbbbbbbbbbbbbbb###a      ",
  "  ##bbbbbbbbbbbbbbbbbbbbb####a     ",
  "  ##bbbbbbbbbbbbbbbbbbbbb#####a    ",
  "  ##bbbbbbbbbbbbbbbbbbbbb######a   ",
  "  ##bbbbbbbbbbb###bbaabbb######b   ",
  "  ##bbbbbbbbb#######ccabbbccc.dbc  ",
  "  ##bbbbbbbb#########ccabbbcccab.  ",
  "  ##bbbbbbbb##becc###bcaabbbaabb.  ",
  "  ##bbbbbbb###eccca###ecaabbbb##.  ",
  "  ##bbbbbbb###cccab###ecabbbbb##.  ",
  "  ##bbbbbbbbbeccabb##becaabbbb##.  ",
  "  ##bbbbbbbbbbbbbb###becabbbbb##.  ",
  "  ##bbbbbbbbbbbbb####eccaabbbb##.  ",
  "  ##bbbbbbbbbbbb####eccaabbbbb##.  ",
  "  ##bbbbbbbbbbb####eccaaabbbbb##.  ",
  "  ##bbbbbbbbbbb###eccaaabbbbbb##.  ",
  "  ##bbbbbbbbbbb###ecaaabbbbbbb##.  ",
  "  ##bbbbbbbbbbbbeeccaabbbbbbbb##.  ",
  "  ##bbbbbbbbbbbbaccaababbbbbbb##.  ",
  "  ##bbbbbbbbbbb###aaaabbbbbbbb##.  ",
  "  ##bbbbbbbbbbb###eabbbbbbbbbb##.  ",
  "  ##bbbbbbbbbbb###ecaabbbbbbbb##.  ",
  "  ##bbbbbbbbbbbbeeecababbbbbbb##.  ",
  "  ##bbbbbbbbbbbbbcccaabbbbbbbb##.  ",
  "  ##bbbbbbbbbbbbbbaaabbbbbbbbb##.  ",
  "  ##bbbbbbbbbbbbbbbbbbbbbbbbbb##.  ",
  "  ##############################.  ",
  "  ##############################.  ",
  "   c.............................  ",
  "                                   ",
  "                                   ",
};

static const char *
dir_file_image[] = {
  "20 21 8 1",
  ". c #ffffff",
  "# c #ffff00",
  "a c #c0c0c0",
  "b c #808080",
  "c c #000080",
  "d c #429aa7",
  "e c #baa0a7",
  "  c none",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "  ccccccc           ",
  " bc#a#a#ac          ",
  " c#e#e#e#ecccccccccd",
  "c#e#e#e#e#a##a#a#aac",
  "ceaeaeaeaa##a#a#a#ec",
  "c#.#.#.#.##a#a#a#aec",
  "c#a#a#a#a#a#a#a#a#ec",
  "c##a#a#a#a#a#a#a#aec",
  "c#a#a#a#a#a#a#a#a#ec",
  "c##a#a#a#a#a#a#a#aec",
  "c#a#a#a#a#a#a#a#a#ec",
  "c##a#a#a#a#a#a#a#aec",
  "c#a#a#a#a#a#a#a#a#ec",
  "ca#e#e#e#e#e#e#e#eec",
  "c#a#a#a#a#a#a#a#a#ec",
  "ceeeeeeeeeeeeeeeeeec",
  "cccccccccccccccccccc",
};

static const char *
normal_file_image[] = {
  "20 21 7 1",
  ". c #000000",
  "# c #ffffff",
  "a c #c0c0c0",
  "b c #808080",
  "c c #000080",
  "d c #429aa7",
  "  c none",
  "  ccccccccccb       ",
  "  c#########ac      ",
  "  c#########aac     ",
  "  c#########a#ac    ",
  "  c#########a##ac   ",
  "  c#########a###ab  ",
  "  c#########dcccc.  ",
  "  c##########bbbb.  ",
  "  c###########aaac  ",
  "  c#############ac  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  cccccccccccccccc  "
};

static const char *
image_file_image[] = {
  " 20 21 12 1",
  ". c #000000",
  "# c #ffffff",
  "a c #c0c0c0",
  "b c #808080",
  "c c #000080",
  "d c #429aa7",
  "e c #baa0a7",
  "f c #0000ff",
  "g c #008000",
  "h c #1a5f67",
  "i c #2f7e88",
  "  c none",
  "  ccccccccccb       ",
  "  c#########ac      ",
  "  c#########aac     ",
  "  c#########a#ac    ",
  "  c#########a##ac   ",
  "  c######dgia###ab  ",
  "  c######giidcccc.  ",
  "  c######iiihhbbb.  ",
  "  c######giiihaaac  ",
  "  c####a#dgig###ac  ",
  "  c####e#########c  ",
  "  c###aea########c  ",
  "  c###eee##ffff##c  ",
  "  c##aeeea#ffff##c  ",
  "  c##eeeee#ffff##c  ",
  "  c########ffff##c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  c##############c  ",
  "  cccccccccccccccc  ",
};

static const char *
html_file_image[] = {
  " 20 21 9 1",
  ". c #000000",
  "# c #ffffff",
  "a c #c0c0c0",
  "b c #808080",
  "c c #000080",
  "d c #429aa7",
  "e c #baa0a7",
  "f c #1a5f67",
  "  c none",
  "aaccccccccccbaaaaaaa",
  "aac#########acaaaaaa",
  "aac#########aacaaaaa",
  "aac##eabababa#acaaaa",
  "aac#########a##acaaa",
  "aac##eb#abbaa###abaa",
  "aac#########dcccc.aa",
  "aac##ebab#baffbfb.aa",
  "aac##########aaaacaa",
  "aac##eabbab#baba#caa",
  "aac##############caa",
  "aac##ebab#bab####caa",
  "aac##############caa",
  "aac##eb#ab#ababa#caa",
  "aac##############caa",
  "aac##eabb#ba#bab#caa",
  "aac##############caa",
  "aac##eb#bab######caa",
  "aac##############caa",
  "aac##############caa",
  "aaccccccccccccccccaa",
};

static const char *
blank_file_image[] = {
  "20 21 1 1",
  "  c none",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
  "                    ",
};

#endif
